"""updated tables2 with assignments

Revision ID: 07a5445e3d62
Revises: b39580ffd33e
Create Date: 2023-07-17 12:43:03.284965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a5445e3d62'
down_revision = 'b39580ffd33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assignments_student_id_users', type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_assignments_student_id_users', 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###
